package com.sanket.tools.nexpad.ui.theme

import androidx.compose.ui.graphics.Color

// Cyber-Nexus System Palette (Deep Space AMOLED)
//val md_theme_dark_primary = Color(0xFFA8E8FF)
val md_theme_dark_primary = Color(0xFF00D4FF)
val md_theme_dark_onPrimary = Color(0xFF003642)
val md_theme_dark_primaryContainer = Color(0xFF00D4FF)
val md_theme_dark_onPrimaryContainer = Color(0xFF00586B)
val md_theme_dark_secondary = Color(0xFFD2BBFF)
val md_theme_dark_onSecondary = Color(0xFF3F008E)
val md_theme_dark_secondaryContainer = Color(0xFF6001D1)
val md_theme_dark_onSecondaryContainer = Color(0xFFC9AEFF)
val md_theme_dark_tertiary = Color(0xFF8AEDFF)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF00D6EE)
val md_theme_dark_onTertiaryContainer = Color(0xFF005963)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF081425)
val md_theme_dark_onBackground = Color(0xFFD8E3FB)
val md_theme_dark_surface = Color(0xFF081425)
val md_theme_dark_onSurface = Color(0xFFD8E3FB)
val md_theme_dark_surfaceVariant = Color(0xFF2A3548)
val md_theme_dark_onSurfaceVariant = Color(0xFFBBC9CF)
val md_theme_dark_outline = Color(0xFF859398)
val md_theme_dark_inverseOnSurface = Color(0xFF263143)
val md_theme_dark_inverseSurface = Color(0xFFD8E3FB)
val md_theme_dark_inversePrimary = Color(0xFF00677E)
val md_theme_dark_surfaceTint = Color(0xFF3CD7FF)
val md_theme_dark_outlineVariant = Color(0xFF3C494E)
val md_theme_dark_scrim = Color(0xFF000000)